-- n1016 - unwanted characters in index name

-- "n1016 "  - yes
DROP TABLE IF EXISTS public."n1016 " CASCADE;
CREATE TABLE public."n1016 "
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "	n1016"  - yes
DROP TABLE IF EXISTS public."	n1016" CASCADE;
CREATE TABLE public."	n1016"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "n.1016"  - yes
DROP TABLE IF EXISTS public."n.1016" CASCADE;
CREATE TABLE public."n.1016"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "n+1016"  - yes
DROP TABLE IF EXISTS public."n+1016" CASCADE;
CREATE TABLE public."n+1016"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "n\n1016" - yes
DROP TABLE IF EXISTS public."n\n1016" CASCADE;
CREATE TABLE public."n\n1016"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "n
-- 1016"     - yes
DROP TABLE IF EXISTS public."n
1016" CASCADE;
CREATE TABLE public."n
1016"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);
