-- n1021 - unwanted characters in sequence name

-- "n1021 "  - yes
DROP TABLE IF EXISTS public."n1021 " CASCADE;
CREATE TABLE public."n1021 "
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "	n1021"  - yes
DROP TABLE IF EXISTS public."	n1021" CASCADE;
CREATE TABLE public."	n1021"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "n.1021"  - yes
DROP TABLE IF EXISTS public."n.1021" CASCADE;
CREATE TABLE public."n.1021"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "n+1021"  - yes
DROP TABLE IF EXISTS public."n+1021" CASCADE;
CREATE TABLE public."n+1021"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "n\n1021" - yes
DROP TABLE IF EXISTS public."n\n1021" CASCADE;
CREATE TABLE public."n\n1021"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);

-- "n
-- 1021"     - yes
DROP TABLE IF EXISTS public."n
1021" CASCADE;
CREATE TABLE public."n
1021"
(
    id integer GENERATED ALWAYS AS IDENTITY NOT NULL PRIMARY KEY
);
